import yaml
import os
import glob

"""Parse config"""
configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

"""Rules"""
include: os.path.join("rules", "0.preflight.smk")
include: os.path.join("rules", "1.qc.smk")
include: os.path.join("rules", "Run.2.mapping.smk")
include: os.path.join("rules", "QC-reports.smk")
include: os.path.join("rules", "Run.3.Mitogenomes.smk")
include: os.path.join("rules", "Run.Mitogenome-reports.smk")
include: os.path.join("rules", "Run.GeneMapping.smk")

"""Mark target rules"""
target_rules = []
def targetRule(fn):
    assert fn.__name__.startswith('__')
    target_rules.append(fn.__name__[2:])
    return fn

"""
Defining the targets dictionary
"""
targets ={'qc':[], 'host':[]}
sample_names = list(config["sample_names"].keys())
#print (sample_names)

rint("\n--- DEBUG ---")
print("Expected fastp output:")
print(os.path.join(dir_fastp, f"{sample_names[0]}_R1.fastq.gz"))

print("\nActual targets:")
for t in targets['qc'][:5]:
    print(t)
print("Total targets:", len(targets['qc']))
print("--- END DEBUG ---\n")

if config['args']['mode'] == "mitogenome":
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}_R1.fastq.gz"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}_R2.fastq.gz"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}.stats.json"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}.stats.html"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_hostcleaned,"{sample}_temp.bam"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_hostcleaned,"{sample}_bamstats.txt"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_hostcleaned,"{sample}_R1.mapped.fastq.gz"),sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_hostcleaned,"{sample}_R2.mapped.fastq.gz"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mapped.bam"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mitogenome_snps_depth.txt"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mitogenome_snps.filtered.vcf.gz"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mitogenome_snps.allele_frequency.txt"), sample=sample_names)
    targets['host'] = os.path.join(dir_hostcleaned, "mitogenome", "merged_mitogenome_snps.filtered.norm.vcf.gz")
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenome", "{sample}_low_cov.bed"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenome", "{sample}_consensus.fasta"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_out, "temp", "{sample}_done.txt"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_reports,"QC","{sample}_host_qc_report.txt"), sample=sample_names)
    targets['qc'] = os.path.join(dir_reports, "final_host_qc_summary.txt")
    targets['host'] = os.path.join(dir_reports, "mitogenome_consensus_summary.tsv")
elif config['args']['mode'] == "gene":
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}.stats.html"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}.stats.json"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}_R1.fastq.gz"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_fastp,"{sample}_R2.fastq.gz"), sample=sample_names)
    targets['qc'] = expand(os.path.join(dir_reports,"QC","{sample}_host_qc_report.txt"), sample=sample_names)
    targets['qc'] = os.path.join(dir_reports, "final_host_qc_summary.txt")

    targets['host'] = os.path.join(dir_hostcleaned, "gene_index.1.bt2")
    targets['host'] = expand(os.path.join(dir_hostcleaned,"{sample}_temp.bam"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenes", "{sample}_mapped.bam"), sample=sample_names),
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenes", "{sample}_mitogenome_snps_depth.txt"), sample=sample_names),
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenes", "{sample}_mitogenome_snps.filtered.vcf.gz"), sample=sample_names),
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenes", "{sample}_low_cov.bed"), sample=sample_names),
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenes", "{sample}_consensus.fasta"), sample=sample_names),
    targets['host'] = expand(os.path.join(dir_out, "temp", "{sample}_done.txt"), sample=sample_names)
    targets['host'] = expand(os.path.join(dir_hostcleaned, "mitogenes", "{sample}_consensus.summary.tsv"), sample=sample_names)
    targets['host'] = os.path.join(dir_reports, "mitogene_consensus_summary.tsv")

@targetRule
rule all:
    input:
        targets['qc'],
        targets['host'],


@targetRule
rule qc:
    input:
        targets['qc']

@targetRule
rule host:
    input:
        targets['host']
