import yaml
import os
import glob

"""Parse config"""
configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

"""Rules"""
include: os.path.join("rules", "0.preflight.smk")
include: os.path.join("rules", "1.qc.smk")
include: os.path.join("rules", "2.mapping.smk")
include: os.path.join("rules", "QC-reports.smk")
include: os.path.join("rules", "3.Mitogenomes.smk")
include: os.path.join("rules", "Mitogenome-reports.smk")


"""Mark target rules"""
target_rules = []
def targetRule(fn):
    assert fn.__name__.startswith('__')
    target_rules.append(fn.__name__[2:])
    return fn

"""
Defining the targets dictionary
"""
targets ={'qc':[], 'host':[]}
sample_names = list(config["sample_names"].keys())
print (sample_names)

# Per-sample targets
qc_per_sample = [
    os.path.join(dir_fastp, "{sample}_R1.fastq.gz"),
    os.path.join(dir_fastp, "{sample}_R2.fastq.gz"),
    os.path.join(dir_fastp, "{sample}.stats.json"),
    os.path.join(dir_fastp, "{sample}.stats.html"),
    os.path.join(dir_hostcleaned, "{sample}_temp.bam"),
    os.path.join(dir_hostcleaned, "{sample}_bamstats.txt"),
    os.path.join(dir_reports, "QC", "{sample}_host_qc_report.txt")
]

host_per_sample = [
    os.path.join(dir_hostcleaned, "{sample}_R1.mapped.fastq.gz"),
    os.path.join(dir_hostcleaned, "{sample}_R2.mapped.fastq.gz"),
    os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mapped.bam"),
    os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mitogenome_snps.vcf.gz"),
    os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mitogenome_snps.filtered.vcf.gz"),
    os.path.join(dir_hostcleaned, "mitogenome", "{sample}_mitogenome_snps.allele_frequency.txt"),
    os.path.join(dir_hostcleaned, "mitogenome", "{sample}_low_cov.bed"),
    os.path.join(dir_hostcleaned, "mitogenome", "{sample}_consensus.fasta")
]

# Global targets (no sample wildcard)
qc_global = [os.path.join(dir_reports, "final_host_qc_summary.txt")]
host_global = [os.path.join(dir_reports, "mitogenome_consensus_summary.tsv")]

# Build final lists for rule all
targets_all = expand(qc_per_sample, sample=sample_names) + qc_global + \
              expand(host_per_sample, sample=sample_names) + host_global

@targetRule
rule all:
    input:
        targets_all

@targetRule
rule qc:
    input:
        expand(qc_per_sample, sample=sample_names) + qc_global 

@targetRule
rule host:
    input:
        expand(host_per_sample, sample=sample_names) + host_global
