import yaml
import os
import glob

"""Parse config"""
configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

"""Rules"""
include: os.path.join("rules", "0.preflight.smk")
include: os.path.join("rules", "1.qc.smk")
include: os.path.join("rules", "2.mapping.smk")
include: os.path.join("rules", "QC-reports.smk")
include: os.path.join("rules", "3.Mitogenomes.smk")
include: os.path.join("rules", "Mitogenome-reports.smk")


"""Mark target rules"""
target_rules = []
def targetRule(fn):
    assert fn.__name__.startswith('__')
    target_rules.append(fn.__name__[2:])
    return fn

"""
Defining the targets dictionary
"""
targets ={'qc':[], 'host':[]}
sample_names = list(config["sample_names"].keys())
print (sample_names)

for sample in sample_names:
    targets['qc'].extend([
        os.path.join(dir_fastp,"{sample}.stats.html"),
        os.path.join(dir_fastp,"{sample}.stats.json"),
        os.path.join(dir_fastp,"{sample}_R1.fastq.gz"),
        os.path.join(dir_fastp,"{sample}_R2.fastq.gz"), 
        os.path.join(dir_hostcleaned,"{sample}_temp.bam"),
        os.path.join(dir_hostcleaned,"{sample}_bamstats.txt"),
        os.path.join(dir_reports,"QC","{sample}_host_qc_report.txt")
    ])
    targets['qc'].append(os.path.join(dir_reports, "final_host_qc_summary.txt"))

# Host targets
for sample in sample_names:
    targets['host'].extend([
        os.path.join(dir_hostcleaned, f"{sample}_R1.mapped.fastq.gz"),
        os.path.join(dir_hostcleaned, f"{sample}_R2.mapped.fastq.gz"),
        os.path.join(dir_hostcleaned, "mitogenome", f"{sample}_mapped.bam"),
        os.path.join(dir_hostcleaned, "mitogenome", f"{sample}_mitogenome_snps.vcf.gz"),
        os.path.join(dir_hostcleaned, "mitogenome", f"{sample}_mitogenome_snps.filtered.vcf.gz"),
        os.path.join(dir_hostcleaned, "mitogenome", f"{sample}_mitogenome_snps.allele_frequency.txt"),
        os.path.join(dir_hostcleaned, "mitogenome", f"{sample}_low_cov.bed"),
        os.path.join(dir_hostcleaned, "mitogenome", f"{sample}_consensus.fasta")
    ])
# add any final summary files
targets['host'].append(os.path.join(dir_reports, "mitogenome_consensus_summary.tsv"))

@targetRule
rule all:
    input:
        targets['qc'] + targets['host'],

@targetRule
rule qc:
    input:
        targets['qc']

@targetRule
rule host:
    input:
        targets['host']
